services:
#  oracle-db:
#    container_name: labotron-oracle-db
#    image: gvenzl/oracle-xe:latest
#    environment:
#      - ORACLE_PASSWORD=12345678
#      - ORACLE_DATABASE=XE
#      - APP_USER=labotron
#      - APP_USER_PASSWORD=123456
#    ports:
#      - "${ORACLE_PORT}:1521"
#      #- "8585:8080"
#    volumes:
#      - oracle_data:/opt/oracle/oradata
#    healthcheck:
#      test: [ "CMD-SHELL", "healthcheck.sh" ]
#      interval: 50s
#      timeout: 10s
#      retries: 5

  postgres:
    container_name: labotron-postgres
    image: postgres:17.6
    ports:
      - "0.0.0.0:${DATASOURCE_PORT}:5432"
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DATASOURCE_DBNAME}
      - POSTGRES_USER=${DATASOURCE_USERNAME}
      - POSTGRES_PASSWORD=${DATASOURCE_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d aid_card -h 127.0.0.1 -p 5432"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  rabbitmq:
    container_name: labotron-rabbitmq  
    image: rabbitmq:3-management
    restart: always
    ports:
      - "${RABBITMQ_PORT}:5672"
      - "${RABBITMQ_MGMT_PORT}:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER:-guest}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS:-guest}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  labotron-service:
    container_name: labotron-service  
    image: ${LABOTRON_SERVICE_IMAGE}
    ports:
      - "${LABOTRON_SERVICE_PORT}:8080"
    environment:
#      - SPRING_PROFILES_ACTIVE=prod   # Spring profile
      - JAVA_OPTS=-Xmx4092m -Xms256m   # JVM memory limits
      - DATASOURCE_URL
      - DATASOURCE_USERNAME
      - DATASOURCE_PASSWORD
      - DATASOURCE_DRIVERS
      - RABBITMQ_HOST
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME
      - RABBITMQ_PASSWORD
    restart: unless-stopped
    volumes:
      - ./logs:/usr/local/tomcat/logs # Persist logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  # Flutter Web Frontend
  labotron-web:
    image: ${LABOTRON_WEB_IMAGE}
    container_name: labotron-web
    ports:
      - "${LABOTRON_WEB_PORT}:80"  # Frontend on standard HTTP port
    environment:
      - API_URL
    restart: always

# Named volumes for proper permissions
volumes:
#  oracle_data:
#    driver: local
  postgres_data:
    name: labotron_postgres_data
    driver: local
  rabbitmq_data:
    name: labotron_rabbitmq_data   # 👈 explicit volume name
    driver: local

